# Generated by Django 3.2.4 on 2021-11-21 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='donation_plea',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=13)),
                ('requirement', models.CharField(max_length=250)),
                ('birth_date', models.IntegerField()),
                ('birth_month', models.CharField(max_length=2)),
                ('birth_year', models.CharField(max_length=4)),
                ('message', models.TextField()),
            ],
        ),
    ]
