# Generated by Django 3.2.4 on 2021-11-21 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation_plea',
            name='gender',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
